src/BrewskiiApp - MVC/BrewskiiApp/Models/Beer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace BrewskiiApp.Models
{
    public class Beer
    {
        public int ID { get; set; }

        [StringLength(60, MinimumLength = 3)]
        [Required]
        [Display(Name = "Beer Name")]
        public string BeerName { get; set; }

        [Display(Name = "Date Tried")]
        [DataType(DataType.Date)]
        public DateTime DateTried { get; set; }

        [RegularExpression(@"^[A-Z]+[a-zA-Z""'\s-]*$")]
        [Required]
        [StringLength(30)]
        [Display(Name = "Beer Type")]
        public string BeerType { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal Rating { get; set; }
    }
}

src/BrewskiiApp - MVC/BrewskiiApp/Models/BeerTypeViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BrewskiiApp.Models
{

    public class BeerTypeViewModel
    {
        public List<Beer> beers;
        public SelectList beerTypes;
        public string BeerTypes { get; set; }
    }
}

src/BrewskiiApp - MVC/BrewskiiApp/Models/ErrorViewModel.cs
using System;

namespace BrewskiiApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/BrewskiiApp - MVC/BrewskiiApp/Models/SeedData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace BrewskiiApp.Models
{
    public class SeedData
    {
        public static void Initialize(IServiceProvider serviceProvider)
        {
            using (var context = new BrewskiiAppContext(
                serviceProvider.GetRequiredService<DbContextOptions<BrewskiiAppContext>>()))
            {
                if (context.Beer.Any())
                {
                    return; //DB has been seeded
                }

                context.Beer.AddRange(
                 
            );
                context.SaveChanges();
            }

        }
    }
}

src/BrewskiiApp - MVC/BrewskiiApp/Controllers/BeersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BrewskiiApp.Models;


namespace BrewskiiApp.Controllers
{
    public class BeersController : Controller
    {
        private readonly BrewskiiAppContext _context;

        public BeersController(BrewskiiAppContext context)
        {
            _context = context;
        }

        // GET: Beers
        public async Task<IActionResult> Index(string beerTypeQuery, string searchString)
        {
            // Use LINQ to get list of genres.
            IQueryable<string> beerQuery = from b in _context.Beer
                                            orderby b.BeerType
                                            select b.BeerType;

            var beers = from b in _context.Beer
                         select b;

            if (!String.IsNullOrEmpty(searchString))
            {
                beers = beers.Where(s => s.BeerName.Contains(searchString));
            }

            if (!String.IsNullOrEmpty(beerTypeQuery))
            {
                beers = beers.Where(x => x.BeerType == beerTypeQuery);
            }

            var beerTypeVM = new BeerTypeViewModel();
            beerTypeVM.beerTypes = new SelectList(await beerQuery.Distinct().ToListAsync());
            beerTypeVM.beers = await beers.ToListAsync();

            return View(beerTypeVM);
        }

        [HttpPost]
        public string Index(string searchString, bool notUsed)
        {
            return "From [HttpPost]Index: filter on " + searchString;
        }

        // GET: Beers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var beer = await _context.Beer
                .FirstOrDefaultAsync(m => m.ID == id);
            if (beer == null)
            {
                return NotFound();
            }

            return View(beer);
        }

        // GET: Beers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Beers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,BeerName,DateTried,BeerType,Rating")] Beer beer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(beer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(beer);
        }

        // GET: Beers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var beer = await _context.Beer.FindAsync(id);
            if (beer == null)
            {
                return NotFound();
            }
            return View(beer);
        }

        // POST: Beers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,BeerName,DateTried,BeerType,Rating")] Beer beer)
        {
            if (id != beer.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(beer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BeerExists(beer.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(beer);
        }

        // GET: Beers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var beer = await _context.Beer
                .FirstOrDefaultAsync(m => m.ID == id);
            if (beer == null)
            {
                return NotFound();
            }

            return View(beer);
        }

        // POST: Beers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var beer = await _context.Beer.FindAsync(id);
            _context.Beer.Remove(beer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BeerExists(int id)
        {
            return _context.Beer.Any(e => e.ID == id);
        }
    }
}

src/BrewskiiApp - MVC/BrewskiiApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BrewskiiApp.Models;

namespace BrewskiiApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/BrewskiiApp - MVC/BrewskiiApp/Views/Beers/Create.cshtml
@model BrewskiiApp.Models.Beer

@{
    ViewData["Title"] = "Create";
}

<head>
    <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
    <script src="beer2.js"></script>
</head>

<!-- This is how we get background images on the page -->
<body style="background-image: url('http://oi68.tinypic.com/21bji40.jpg');">
</body>




<h2>Create</h2>

<style>
    * {
        box-sizing: border-box;
    }

    /* Create two equal columns that floats next to each other */
    .column {
        float: left;
        width: 50%;
        padding: 10px;
        height: 300px; /* Should be removed. Only for demonstration */
    }

    /* Clear floats after the columns */
    .row:after {
        content: "";
        display: table;
        clear: both;
    }
</style>
<!--
This is our Beer search form that connects to the API via ajax call.
beer2.js has our call info located in the wwwroot folder
-->
<div class="row">
    <div class="column">
        <h4><b>Search for beer.</b></h4>
        <hr />
        <form method=" " post>

            <fieldset>
                <label for="br"><b>Enter a beer:</b> </label>
                <input type="text" name="br" id="br">
                <input type="submit" name="submit_beer" id="beerSub">
                <a asp-action="Create">Clear</a>
            </fieldset>
        </form>
        <ul>
            <img id="beerImg"><img>
            <li><span><b>Beer Searched:</b> </span><span id="sb"></span></li>
            <li><span><b>Beer Type:</b> </span><span id="bt"></span></li>
            <li><span><b>ABV:</b> </span><span id="abv"></span><span>%</span></li>
            <li><span><b>Brewery:</b> </span><span id="brew"></span></li>
            <li><span><b>Location:</b> </span><span id="loc"></span></li>
            <li><span><b>BreweryDB ID:</b> </span><span id="id"></span></li>
            <!-- <li><img id="brewImg"><img></li> BREWERY IMAGE-->
        </ul>
        <p><b>Beer with similar names:</b></p>
        <ul>
            <li><span><b>Try:</b> </span><span id="try1"></span></li>
            <li><span><b>Try:</b> </span><span id="try2"></span></li>
        </ul>
    </div>


    <div class="column">
        <h4><b>Add a beer to your list.</b> (<a asp-action="Index">View Your List</a>)</h4>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="BeerName" class="control-label"></label>
                        <input asp-for="BeerName" class="form-control" />
                        <span asp-validation-for="BeerName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DateTried" class="control-label"></label>
                        <input asp-for="DateTried" class="form-control" />
                        <span asp-validation-for="DateTried" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="BeerType" class="control-label"></label>
                        <input asp-for="BeerType" class="form-control" />
                        <span asp-validation-for="BeerType" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Rating" class="control-label"></label>
                        <input asp-for="Rating" class="form-control" />
                        <span asp-validation-for="Rating" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

src/BrewskiiApp - MVC/BrewskiiApp/Views/Beers/Delete.cshtml
@model BrewskiiApp.Models.Beer

@{
    ViewData["Title"] = "Delete";
}

<!-- This is how we get background images on the page -->
<body style="background-image: url('http://oi68.tinypic.com/21bji40.jpg');">
</body>

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Beer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BeerName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BeerName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateTried)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateTried)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BeerType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BeerType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

src/BrewskiiApp - MVC/BrewskiiApp/Views/Beers/Details.cshtml
@model BrewskiiApp.Models.Beer

@{
    ViewData["Title"] = "Details";
}

<!-- This is how we get background images on the page -->
<body style="background-image: url('http://oi68.tinypic.com/21bji40.jpg');">
</body>

<h2>Details</h2>

<div>
    <h4>Beer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BeerName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BeerName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateTried)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateTried)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BeerType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BeerType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/BrewskiiApp - MVC/BrewskiiApp/Views/Beers/Edit.cshtml
@model BrewskiiApp.Models.Beer

@{
    ViewData["Title"] = "Edit";
}

<!-- This is how we get background images on the page -->
<body style="background-image: url('http://oi68.tinypic.com/21bji40.jpg');">
</body>

<h2>Edit</h2>

<h4>Beer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="BeerName" class="control-label"></label>
                <input asp-for="BeerName" class="form-control" />
                <span asp-validation-for="BeerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateTried" class="control-label"></label>
                <input asp-for="DateTried" class="form-control" />
                <span asp-validation-for="DateTried" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BeerType" class="control-label"></label>
                <input asp-for="BeerType" class="form-control" />
                <span asp-validation-for="BeerType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

src/BrewskiiApp - MVC/BrewskiiApp/Views/Beers/Index.cshtml
@model BrewskiiApp.Models.BeerTypeViewModel

@{
    ViewData["Title"] = "Index";
}

<head>
    <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
    <script src="beer2.js"></script>
</head>

<!-- This is how we get background images on the page -->
<body style="background-image: url('http://oi68.tinypic.com/21bji40.jpg');">
</body>

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Beers" asp-action="Index" method="get">
    <p>
        <select asp-for="beerTypes" asp-items="Model.beerTypes">
            <option value="">All</option>
        </select>

        Beer Name: <input type="text" name="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.beers[0].BeerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.beers[0].DateTried)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.beers[0].BeerType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.beers[0].Rating)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.beers)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.BeerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateTried)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BeerType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rating)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

src/BrewskiiApp - MVC/BrewskiiApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About Brewskii++";
    ViewBag.LineCount = 33;
    ViewBag.CharacterCount = 2295;
}
<!-- This is how we get background images on the page -->
<body style="background-image: url('http://oi68.tinypic.com/21bji40.jpg');">
</body>

<h3>@ViewBag.Message</h3>
<h4><u>About us:</u></h4>

<html>
<div>
<pre class="prettyprint prettyprint-text-doc linenums">
Brewski++ is a personal beer logging website which allows the user to add beers that they have tried along with other useful information about the beer. 
Additionally, find useful information about your beers with the search field and add them to your list!

The Brewskii++ uses one of the most common design patterns in object oriented programming, the factory pattern. 
We create objects behind the scenes without delivering any of the implementation to our user. 
An example would be the user being able to create a beer and add it to a list without seeing any of the logic behind the operation.
We are using a Model - View - Controller modular design for our website implementation. For simplicity in this document, 
we will analyze these three modules separately and how they relate to the front-end and back-end view of our website.
                                 
             _, . '__ . 
          '_(_0o),(__)o().
        ,o(__),_)o(_)O,(__)o                     
      o(_,-o(_ )(),(__(_)oO)_
      .O(__)o,__).(_ )o(_)Oo_)
  .----|   |   |   |   |   |_)0
 /  .--|   |   |   |   |   |,_)
|  /   |   |   |   |   |   |o(_)
|  |   |   |   |   |   |   |_/`)
|  |   |   |   |   |   |   |O_) 
|  |   |   |   |   |   |   |
|  \   |   |   |   |   |   |
 \  '--|   |   |   |   |   |
  '----|   |   |   |   |   |
       |   |   |   |   |   |
       \   \   \   /   /   /
        `"""""""""""""""""`
</pre>
</div>
</html>

src/BrewskiiApp - MVC/BrewskiiApp/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<!-- This is how we get background images on the page -->
<body style="background-image: url('http://oi68.tinypic.com/21bji40.jpg');">
</body>
@{
    ViewBag.Title = "Contact Us";
}


<h3>@ViewBag.Message</h3>
<h4><u>Contact Information:</u></h4>

<html>
<pre class="prettyprint prettyprint text-doc-linenums">
<div>
<address>
    Indiana University Southeast
    4201 Grant Line Rd.
    New Albany, IN 47150
    (812)-867-5309
</address>
<address>
    <strong>Member 1:</strong>  <a href="https://github.com/AndrewMeiners">Andrew Meiners</a>
    <strong>Email: </strong> <a href="mailto:AMeiners@iu.edu">ameiners@iu.edu</a><br />
    <strong>Member 2: </strong> <a href="https://github.com/DanielRussell-druss">Daniel Russell</a>
    <strong>Email: </strong> <a href="mailto:AMeiners@iu.edu">daleruss@iu.edu</a><br />
    <strong>Member 3:</strong>  <a href="https://github.com/HXNGUY01"> Hung Nguyen</a>
    <strong>Email: </strong> <a href="mailto:hungnguyenpsn@gmail.com">hungnguyenpsn@gmail.com</a><br />
</address>
</div>
</pre>
</html>

src/BrewskiiApp - MVC/BrewskiiApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Beer Cooler";
}

<!-- This is how we get background images on the page -->
<body style="background-image: url('http://oi68.tinypic.com/21bji40.jpg');">
</body>

<h2>The Beer Cave</h2>

<p>Hello world from the Beer Cave!</p>

src/BrewskiiApp - MVC/BrewskiiApp/Views/Home/Welcome.cshtml
@{
    ViewData["Title"] = "Welcome";
}

<!-- This is how we get background images on the page -->
<body style="background-image: url('http://oi68.tinypic.com/21bji40.jpg');">
</body>

<h2>Welcome</h2>

<ul>
    @for (int i = 0; i < (int)ViewData["NumTimes"]; i++)
    {
        <li>@ViewData["Message"]</li>
    }
</ul>

src/BrewskiiApp - MVC/BrewskiiApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Brewskii++</title>
    
    
    <style>
        * {
            box-sizing: border-box;
        }

        /* Create two equal columns that floats next to each other */
        .footer {
            position: absolute;
            right: 0;
            bottom: 0;
            left: 0;
            padding: 1rem;
            background-color: #efefef;
            text-align: center;
        }

    </style>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-area="" asp-controller="Beers" asp-action="Create" class="navbar-brand">Brewskii++</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a asp-area="" asp-controller="Beers" asp-action="Index">My List</a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
            </ul>
        </div>
    </div>
</nav>

<partial name="_CookieConsentPartial" />

<div class="container body-content">
    @RenderBody()
</div>

<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment exclude="Development">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>

 @RenderSection("Scripts", required: false)
    <div class="footer">
        <h5>@Html.ActionLink("Home ", "Create", "Beers")     @Html.ActionLink("About ", "About", "Home")     @Html.ActionLink("Contact", "Contact", "Home")</h5>
        <p>&copy; 2018 Brewskii. All Rights Reserved.</p>
    </div>
</body>
</html>